### ISSUE TITLE
Sample output

### ISSUE THREAD

**Issue by cfenz** [Maboroshy/Note-Station-to-html#1]
[remaboroshynotestationtomarkdownconverttohtml.zip](https://github.com/Maboroshy/Note-Station-to-html/files/3992544/remaboroshynotestationtomarkdownconverttohtml.zip)

**Comment by Maboroshy** [comment]
I've uploaded the new version that should fix the issue. Please, test and let me know if it works.

**Comment by Maboroshy** [comment]
Comment in #2 says it fixed.
