### ISSUE TITLE
Treatment of media files

### ISSUE THREAD

**Issue by cfenz** [Maboroshy/Note-Station-to-html#2]
The issue with in-line images being stripped is fixed, but wondering if it is possible to have the media files embedded in the resultant HTML rather than in a separate folder?  Asking because I am seeking to import the HTML files into another program (OneNote) and that program does not elegantly handle outboard media files.  Looks like there's a resource here: https://weblog.west-wind.com/posts/2018/Nov/01/Creating-an-HTML-Packager.

**Comment by Maboroshy** [comment]
As you've posted there are apps that do that well. I wasn't able to find a Python library that does that out of the box and writing one is the amount of work equal to writing this script.

I won't take on this myself. I'm ready to merge any commit that implements your request.
